version: '3.8'

services:
  naturalpet:
    container_name: naturalpet-app
    build:
      context: .
    expose:
      - "80"
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      - naturalpet

volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
